export const INTELIX_ERRORS: Record<string, string> = {
  '3001': '¡Uy! Parece que olvidaste escribir tu correo electrónico. Por favor agrégalo para enviarte tu confirmación.',
  '3002': 'El correo que ingresaste no parece válido. Revisa que esté bien escrito (ejemplo: tu_correo@gmail.com).',
  '3003': 'No olvides ingresar el número telefónico que deseas portar.',
  '3004': 'El número telefónico debe tener exactamente 10 dígitos. ¡Revísalo por favor!',
  '3005': 'Necesitamos el IMEI de tu equipo para continuar.',
  '3006': '¡Ojo! El IMEI solo debe llevar números. Asegúrate de que no haya letras ni símbolos.',
  '3007': 'Por favor indícanos tu nombre para saber con quién tenemos el gusto.',
  '3008': 'Tus apellidos son necesarios para registrar tu línea.',
  '3009': 'Parece que hay caracteres extraños en tus apellidos. Usa solo letras y espacios, por favor.',
  '3010': 'Tu nombre contiene caracteres no permitidos. Usa únicamente letras y espacios.',
  '3011': 'No olvides seleccionar un plan de migración.',
  '3024': 'El plan seleccionado no es válido actualmente. Por favor elige otra opción.',
  '3013': 'Cuéntanos, ¿de qué estado nos visitas? El estado de nacimiento es requerido.',
  '3014': 'El estado que seleccionaste no coincide con nuestros registros válidos. Vuelve a intentarlo.',
  '3015': 'El NIP es súper importante para autorizar tu portabilidad. ¡No lo olvides!',
  '3016': 'El NIP de portabilidad debe tener exactamente 4 números. Revísalo bien.',
  '3017': 'Necesitamos saber tu fecha de nacimiento para confirmar que eres mayor de edad.',
  '3018': 'El formato de tu fecha de nacimiento debe ser Día/Mes/Año (ejemplo: 03/03/1993).',
  '3019': 'Tu CURP es necesario para completar el registro.',
  '3020': 'El formato de la CURP que ingresaste no parece ser el correcto. Tiene 18 caracteres (letras y números).',
  '3021': 'El RFC es obligatorio.',
  '3022': 'El RFC que ingresaste tiene un formato incorrecto. ¡Verifícalo, por favor!',
  '3023': '¡Tranquilo! Ya estamos procesando una solicitud para este número. Pronto tendrás noticias nuestras.',
};
