import { chromium } from 'playwright';
const BASE = process.env.VERCEL_PREVIEW_URL.replace(/\/$/, '');
const S = process.env.VERCEL_AUTOMATION_BYPASS_SECRET;
const b = await chromium.launch();
const ctx = await b.newContext({ extraHTTPHeaders: { 'x-vercel-protection-bypass': S } });
const p = await ctx.newPage();
const resp = await p.goto(`${BASE}/admin/login`, { waitUntil: 'domcontentloaded' });
console.log('status', resp.status(), 'url', p.url());
const html = await p.content();
console.log('len', html.length);
console.log('title', await p.title());
console.log('has email input:', html.includes('type="email"'));
console.log('snippet:', html.replace(/\s+/g, ' ').slice(0, 600));
await b.close();
