import { chromium } from 'playwright';
const BASE = process.env.VERCEL_PREVIEW_URL.replace(/\/$/, '');
const S = process.env.VERCEL_AUTOMATION_BYPASS_SECRET;
const b = await chromium.launch();
const ctx = await b.newContext({ extraHTTPHeaders: { 'x-vercel-protection-bypass': S } });
const p = await ctx.newPage();
p.on('console', m => console.log('CONSOLE', m.type(), m.text()));
p.on('response', r => { if (r.url().includes('/api/')) console.log('API', r.status(), r.url().replace(BASE,'')); });

await p.goto(`${BASE}/admin`);
await p.fill('input[type="email"]', process.env.QA_ADMIN_EMAIL);
await p.fill('input[type="password"]', process.env.QA_ADMIN_PASSWORD);
await p.click('button[type="submit"]');
await p.waitForURL('**/admin/dashboard');
console.log('--- on dashboard ---');
await p.click('a[href="/admin/leads"]');
await p.waitForURL('**/admin/leads');
await p.waitForTimeout(4000);
console.log('URL:', p.url());
console.log('leadsBody HTML:', (await p.innerHTML('#leadsBody')).slice(0, 1500));
console.log('rows with data-id:', await p.locator('#leadsBody tr[data-id]').count());
await b.close();
